name: Run Tests and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt
   
    - name: Run tests
      run: |
        pytest tests/ -v
       
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: .pytest_cache/v/cache/lastfailed
  
  deploy:
    needs: test # Cette ligne assure que le job de déploiement n'est exécuté que si les tests réussissent
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Déploie uniquement lors d'un push sur main
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}